### ISSUE TITLE
Unknown command using any channel or command

### ISSUE THREAD

**Issue by AWL-Gaming** [egebilecen/PZServerDiscordBot#1]
Hello, the bot is not accepting any of the mentioned commands on Discord. Using a new bot token, Windows environment variables are set, and the bot is having administrator permissions.
![image](https://user-images.githubusercontent.com/22678541/164597888-93f57d54-a787-4edc-8310-03ac34d5c13f.png)

**Comment by egebilecen** [comment]
Thanks for your report. This issue should be fixed in #[569768a](https://github.com/egebilecen/PZServerDiscordBot/commit/569768a9bb6df045fd30fd614ab69d6acbeee38a). Please download this new binary release from [here](https://github.com/egebilecen/PZServerDiscordBot/releases/tag/v1.0.1).
