### ISSUE TITLE
server freezing unless I press enter ?

### ISSUE THREAD

**Issue by lapochka8** [egebilecen/PZServerDiscordBot#100]

**Comment by egebilecen** [comment]
Hello, please be more elaborate.

**Comment by lapochka8** [comment]
My apologies, server freezes up in game. Not sure if its a PZ issue or the discord bot issue, but unless I select the console and spam enter, the server wont unfreeze.

**Comment by egebilecen** [comment]
I feel like it's a problem on your end because you shouldn't be able to write anything into console anyway when you launch the bot.

**Comment by lapochka8** [comment]
so, im not writing anything in the console.
I have to select the bot, and then spam enter to get the code to unstick while its running.

**Comment by egebilecen** [comment]
It is really bizarre. I am not sure what causes it honestly.

**Comment by lapochka8** [comment]
all good, its a great bot either way. Thank you for your work on this.
