### ISSUE TITLE
Localization of Traditional Chinese

### ISSUE THREAD

**Issue by retsnimle** [egebilecen/PZServerDiscordBot#102]
[TraditionalChinese.zip](https://github.com/egebilecen/PZServerDiscordBot/files/12913857/TraditionalChinese.zip)
Hi, this is a localized translation of Traditional Chinese, hope it helps.

**Comment by egebilecen** [comment]
Hey, thank you for sharing your Traditional Chinese translation! Could you tell me how Traditional Chinese written in your language? So I can add it without using English word for Traditional Chinese. Also a brief description about translation in your own language would be appreciated. Something like "Traditional Chinese translation of the bot." in Traditional Chinese.

**Comment by retsnimle** [comment]
It's called "繁體中文"
And here's the description: "繁體中文的本地化翻譯版本"

**Comment by egebilecen** [comment]
I merged the translation. It should be available in `!localization` command in like 10-15 minutes.

**Comment by egebilecen** [comment]
I am glad you liked the bot. :) Don't forget to leave a star to the repo :)
