### ISSUE TITLE
Localization of French

### ISSUE THREAD

**Issue by Mr-Altir** [egebilecen/PZServerDiscordBot#104]
Hello, I've just completed the translation into French. It might not be perfect, and I will have it reviewed by peers. I wanted to tell you that your work is outstanding and I hope to see a Linux version soon. You are the best, keep it up!

[french.json](https://github.com/egebilecen/PZServerDiscordBot/files/12964677/french.json)

**Comment by egebilecen** [comment]
Hey! Thank you for sharing your translation, I will try to add it by this evening.

Also, could you tell me how French written in your language? So I can add it without using English word for French. In addition, a brief description about translation in your own language would be appreciated. Something like "French translation of the bot." in French.

**Comment by Mr-Altir** [comment]
Hello,

Thank you for your message. 

I confirm that "French" is translated as "Français" in French. Regarding the description you asked for: "Traduction française du bot." means "French translation of the bot." in English.

Please don't hesitate if you have any other questions or need further clarifications.

Best regards,

**Comment by egebilecen** [comment]
Hey, I am sorry for the delay. I been quite busy last couple days, I will hopefully get it added this morning, thank you for your patience.

**Comment by egebilecen** [comment]
I merged the translation. It should appear in bot in like 10-15 minutes. :)
