### ISSUE TITLE
exe cant recognize bot_token.txt file

### ISSUE THREAD

**Issue by daniel2231** [egebilecen/PZServerDiscordBot#109]
![image](https://github.com/egebilecen/PZServerDiscordBot/assets/39212398/bcb5195e-dd9a-4e45-8f5f-e490cc7185fc)

I have done all the required steps, but somehow the discord bot cant seem to find the bot_token.txt file. 

Error message:
Couldn't retrieve bot token from "bot_token.txt" file.
Please refer to "https://github.com/egebilecen/PZServerDiscordBot#writing-the-discord-bot-token-into-file".

**Comment by egebilecen** [comment]
Hey, you probably named it as `bot_token.txt.txt`. Try to delete first `.txt` by right clicking to file and then selecting rename option.
