### ISSUE TITLE
ISSUE

### ISSUE THREAD

**Issue by saro8802** [egebilecen/PZServerDiscordBot#111]
Is this an issue?
![Screenshot 2023-05-03 203047](https://github.com/egebilecen/PZServerDiscordBot/assets/97031570/3e951fab-c58d-461a-a78e-ec97c35b81aa)

**Comment by egebilecen** [comment]
Hey, which version causes this warning?

**Comment by egebilecen** [comment]
Assuming the last version, I downloaded it and I got the same warning from Microsoft Defender. However, I put it into virus total ([link here](https://www.virustotal.com/gui/file/a5d5a0c99c43c602153d806dd7008b7647ef7cc05ff812de5fac45c7b14bdc75)), and doesn't seem to have any virus problem except few false positives.

**Comment by saro8802** [comment]
ok ty
