### ISSUE TITLE
Localization of Traditional Chinese

### ISSUE THREAD

**Issue by retsnimle** [egebilecen/PZServerDiscordBot#112]
Hi there. 
I fixed some translations that didn't work well, here is the modified json.
[TraditionalChinese.zip](https://github.com/egebilecen/PZServerDiscordBot/files/13351940/TraditionalChinese.zip)

**Comment by egebilecen** [comment]
Hey, I will update the translation in couple days, hopefully. Thank you.

**Comment by egebilecen** [comment]
Hey, sorry for the delay. This update has been merged now. Thank you for working on translation!
