### ISSUE TITLE
Feature suggestion: After !server_cmd command, display server replay

### ISSUE THREAD

**Issue by retsnimle** [egebilecen/PZServerDiscordBot#113]
Hi there.
Is it possible to display server reply after using !server_cmd command, just like RCON Cli?
I would be very appreciative if this could be done!

**Comment by egebilecen** [comment]
Hey, this is very tricky. Server constantly prints out messages so it's not really feasible to understand if the output belongs to a command or something else. Also, it's not easy to determine when command output is going to end so I will need to deny this request unfortunately.
