### ISSUE TITLE
non Amount for additems command in bot

### ISSUE THREAD

**Issue by PgRusher** [egebilecen/PZServerDiscordBot#117]
Hello
 I installed your project zomboid discord bot everything is good and
works well but there is a problem in additem its worked well but I
can't set the amount for that additem in the discord bot so I requested
to you if you can add it.
thanks

**Comment by PgRusher** [comment]
oh now i see !server_cmd its worked thanks :D

**Comment by egebilecen** [comment]
Hey, no problem. :) Enjoy the bot!
