### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by 6--** [egebilecen/PZServerDiscordBot#12]
Hello,

Can i please request an:

- Auto backup
- Auto restore
~~- Auto start up if the !stop_server command is not sent~~

Found this PZ backup utility, was really helpful
[Backup and Restore.zip](https://github.com/egebilecen/PZServerDiscordBot/files/9685042/Backup.and.Restore.zip)

The utility file only backup:
C:\Users\Administrator\Zomboid\Saves\Multiplayer\servertest

Is it possible to also backup these folders?
C:\Users\Administrator\Zomboid\Server\ (server settings)
C:\Users\Administrator\Zomboid\db\ (server.db file (accounts))
C:\Users\Administrator\Zomboid\Lua\ (mods usually save some of the settings in this file)

Thanks alot!

**Comment by egebilecen** [comment]
I will see what can be done.

**Comment by egebilecen** [comment]
Backup command is added with #34
