### ISSUE TITLE
Bot Auto server status

### ISSUE THREAD

**Issue by PgRusher** [egebilecen/PZServerDiscordBot#120]
Hi 
there is an option for Bot that shows server status automatically when the server is off or is on or if its haven't can you please add it?

**Comment by egebilecen** [comment]
We already have `!server_status` command. Could you be more elobrate on your suggestion?

**Comment by PgRusher** [comment]
What I mean is that it should automatically announce the status of the method or whether the server is off, for example, when the server is off, it should say that the server is off in one of the public channels, and if it is not off, it should write that the server is on, not automatically. Manually

**Comment by egebilecen** [comment]
I don't think adding this feature enhances anything. People can already check the server status using `!server_status` command. It is not restricted.
