### ISSUE TITLE
Localization of Italian

### ISSUE THREAD

**Issue by Kimani88** [egebilecen/PZServerDiscordBot#121]
Hello,

I took the trouble to help with the translation into Italian of your bot.
I hope it is appreciated. You can find it attached.

Kimani

[italian.zip](https://github.com/egebilecen/PZServerDiscordBot/files/13837788/italian.zip)

**Comment by egebilecen** [comment]
Hey! Thank you for sharing your translation, I will try to add it by this evening.

Also, could you tell me how Italian written in your language? So I can add it without using English word for Italian. In addition, a brief description about translation in your own language would be appreciated. Something like "Italian translation of the bot." in Italian.

**Comment by Kimani88** [comment]
Italian = Italiano

"Italian translation of the bot." = "Traduzione in Italiano del Bot"
