### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MiX74P3** [egebilecen/PZServerDiscordBot#126]
**Describe the bug**
I download only get these 3 files. https://i.imgur.com/Tl7GmRd.png
I execute exe and i get this
Couldn't retrieve bot token from "bot_token.txt" file.
Please refer to "https://github.com/egebilecen/PZServerDiscordBot#writing-the-discord-bot-token-into-file".
**To Reproduce**
Steps to reproduce the behavior.
execute exe
**Expected behavior**
doesnr load
**Screenshots**

**Additional context**

**Comment by egebilecen** [comment]
Please follow the steps listed in the link of error.
