### ISSUE TITLE
[SUPPORT] I can't change the location

### ISSUE THREAD

**Issue by ImFeelix** [egebilecen/PZServerDiscordBot#127]
Hey! All good? o/

I'm having difficulty changing the localization to "brazilian_portuguese", as the bot returns the following message after running the "!localization brazilian_portuguese" command: Couldn't find brazilian_portuguese localization!

I added the file inside the "Localization" folder which is located in the root of Project Zomboid. I'm a little confused at this stage and decided to ask you for help, as I'm sure I'm doing something wrong.

Thank you for your support!

**Comment by egebilecen** [comment]
Hey there. You don't need to do any file operations for loading a translation. You just need to get the translation name using `!localization` command and type `!localization <name listed>`. So let's say you want to enable `Português Brasileiro`. Just type `!localization "Português Brasileiro"` command.

![image](https://github.com/egebilecen/PZServerDiscordBot/assets/29331682/c68d4c78-223e-4ecd-bc42-20e61fa89572)
