### ISSUE TITLE
change of language

### ISSUE THREAD

**Issue by eduKenzay** [egebilecen/PZServerDiscordBot#134]
I have read the complete installation guide, however I still don't know how I can change the language of my bot, where should I put the json file, could you help me with the process?

**Comment by egebilecen** [comment]
Hey. You can use `!localization` command. For example, `!localization "繁體中文"`. If you enjoy the bot, please consider to leave a star to the repository. 😌 You don't need to do anything manually.

See the picture below:
![image](https://github.com/egebilecen/PZServerDiscordBot/assets/29331682/0bcd0d77-b020-46e4-9252-3805ab661226)
