### ISSUE TITLE
[LOCALIZATION]

### ISSUE THREAD

**Issue by Femiasty** [egebilecen/PZServerDiscordBot#138]
**Translated language's name in English:**
Polish

**How is the translated language written in the translated language?**
Polski

**A brief description of the translation in the translated language:**
Polska translacja bota (Which is translated as "Polish translation of the bot.")

*Do not forget to attach the zip file that contains the translation.*
[polish.json](https://github.com/user-attachments/files/15776982/polish.json)

**Comment by egebilecen** [comment]
Hey, thank you for the translation! I merged the it. It should be available in `!localization` command in like 10-15 minutes.
