### ISSUE TITLE
[LOCALIZATION] Russian

### ISSUE THREAD

**Issue by VladimirDudokin** [egebilecen/PZServerDiscordBot#142]
**Translated language's name in English:**
- Russian

**How is the translated language written in the translated language?**
- Русский

**A brief description of the translation in the translated language:**
- Перевод бота на русский язык.

[russian_robot_v1.0.1.zip](https://github.com/user-attachments/files/15944079/russian_robot_v1.0.1.zip)

**Comment by egebilecen** [comment]
Hello. We already have a Russian robot translate. What this version is? An update to old version or different translate?

**Comment by egebilecen** [comment]
Okay, I compared the current translate and the new one. It seems to have some fixes. I will update it in a moment.

**Comment by egebilecen** [comment]
I have updated the translation. It should appear in `!localization` in 10 minutes if there is a recent cache.

**Comment by VladimirDudokin** [comment]
Hi! The translation was not bad, but it broke variables and emoticons. Corrected it.

**Comment by egebilecen** [comment]
Thank you!
