### ISSUE TITLE
[BUG] progressively worse duplicate messages in server

### ISSUE THREAD

**Issue by StewBagger** [egebilecen/PZServerDiscordBot#156]
**Describe the bug**
Over time the bot starts to create duplicate messages when communicating from Discord to the server. Eventually it gets to a point where its posting 6+ messages at a time. This is fixed by gracefully taking the server down and closing the console and restarting fresh.

**To Reproduce**
Server console is running for multiple hours.

**Expected behavior**
When communicating from the Discord to the Server it only relays a single instance of the message.

**Screenshots**
![image](https://github.com/user-attachments/assets/f46b6760-3ddc-4e56-9e71-9ea8583888ba)

**Additional context**
I'm unsure if this is a configuration issue on my end but I don't know how else to reach out.

**Comment by egebilecen** [comment]
Hey, you already closed the issue but I just wanted to let others know that this is not an issue with the bot as bot doesn't send any in-game messages other than the restart notification. So this is most likely an issue with a mod in your server. 😊
