### ISSUE TITLE
[LOCALIZATION] <Simplified Chinese>

### ISSUE THREAD

**Issue by aayorishy** [egebilecen/PZServerDiscordBot#160]
**Translated language's name in English:**
Simplified Chinese

**How is the translated language written in the translated language?**
Simplified Chinese

**A brief description of the translation in the translated language:**
Chinese translation of the bot.

*Do not forget to attach the zip file that contains the translation.*
[Chinese.zip](https://github.com/user-attachments/files/16504569/Chinese.zip)

**Comment by aayorishy** [comment]
> 嘿，请用简体中文写下字段（语言名称、描述），而不是英文。

简体中文
简体中文本地汉化翻译

**Comment by aayorishy** [comment]
> Hey, please write the fields (language's name, description) in simplified Chinese, not in English.

简体中文
简体中文本地汉化翻译

**Comment by egebilecen** [comment]
Thanks! I will add the translation in a moment.

**Comment by egebilecen** [comment]
Added. It should appear in 15 minutes or please restart the bot in like 5 minutes for it to appear in the list.
