### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by aayorishy** [egebilecen/PZServerDiscordBot#161]
[pzbot.log](https://github.com/user-attachments/files/16508075/pzbot.log)

**Comment by egebilecen** [comment]
Hello, please provide details.

**Comment by aayorishy** [comment]
When I try to enable the bot, it always pops up this error
---------------
Exception: System.Net.WebException
Message: Unable to connect to remote server
Stack trace: 在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Date: 06/08/2024 09:08:16 UTC
Bot Version: v1.11.5
---------------

**Comment by aayorishy** [comment]
![image](https://github.com/user-attachments/assets/126c2338-6d24-46b2-a980-8d9ad1d17655)
Did I do something wrong?

**Comment by egebilecen** [comment]
Is bot online in the Discord? Did you check it?

**Comment by aayorishy** [comment]
> Is bot online in the Discord? Did you check it?

icheck，bot is offline

**Comment by egebilecen** [comment]
So this connection error is related to the discord API which it says cannot connect to the server. This basically means your computer cannot reach to discord server. I presume you are in China. Do you use VPN to access to discord?

**Comment by aayorishy** [comment]
> So this connection error is related to the discord API which it says cannot connect to the server. This basically means your computer cannot reach to discord server. I presume you are in China. Do you use VPN to access to discord?

yep

**Comment by aayorishy** [comment]
> So this connection error is related to the discord API which it says cannot connect to the server. This basically means your computer cannot reach to discord server. I presume you are in China. Do you use VPN to access to discord?

oh...i see!

**Comment by egebilecen** [comment]
Okay. It seems like your VPN doesn't affect the whole... computer? And only affect various processes. Be sure to use a VPN that, well..., effect the whole processes / applications in the computer. 😊

**Comment by aayorishy** [comment]
> Okay. It seems like your VPN doesn't affect the whole... computer? And only affect various processes / applications. Be sure to use a VPN that, well..., affect the whole processes / applications in the computer. 😊

thanks for ur help.
