### ISSUE TITLE
BOT STILL NOT WORK

### ISSUE THREAD

**Issue by aayorishy** [egebilecen/PZServerDiscordBot#163]
I've tried enabling the VPN, but it still doesn't seem to work. I'm not sure if I'm having a problem somewhere?
![image](https://github.com/user-attachments/assets/e3d373e9-f539-4275-8a63-24bc393c7848)

**Comment by egebilecen** [comment]
Hey, I can't really help you unfortunately as this is a problem outside of the bot. I never used VPN, so...

**Comment by aayorishy** [comment]
> Hey, I can't really help you unfortunately as this is a problem outside of the bot. I never used VPN, so...

I'm not sure if it's because I set it up wrong. It's okay. I appreciate ur willingness to help.

**Comment by egebilecen** [comment]
> > Hey, I can't really help you unfortunately as this is a problem outside of the bot. I never used VPN, so...
> 
> I'm not sure if it's because I set it up wrong. It's okay. I appreciate ur willingness to help.

If there was a problem with setup, bot would print it to the console.

**Comment by egebilecen** [comment]
Could you send the log file again after you enabled the VPN?

**Comment by aayorishy** [comment]
> Could you send the log file again after you enabled the VPN?

[pzbot.log](https://github.com/user-attachments/files/16508518/pzbot.log)

**Comment by aayorishy** [comment]
---------------
Exception: System.Net.Http.HttpRequestException
Message: 发送请求时出错。
Stack trace: 在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.Net.Rest.DefaultRestClient.<SendInternalAsync>d__14.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.Net.Rest.DefaultRestClient.<SendAsync>d__11.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.Net.Queue.RestRequest.<SendAsync>d__19.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   在 Discord.Net.Queue.RequestBucket.<SendAsync>d__20.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.Net.Queue.RequestQueue.<SendAsync>d__15.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.API.DiscordRestApiClient.<SendInternalAsync>d__78.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.API.DiscordRestApiClient.<SendAsync>d__73`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.API.DiscordRestApiClient.<GetBotGatewayAsync>d__81.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__34.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 Discord.API.DiscordSocketApiClient.<ConnectInternalAsync>d__34.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.API.DiscordSocketApiClient.<ConnectAsync>d__33.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.WebSocket.DiscordSocketClient.<OnConnectingAsync>d__114.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.ConnectionManager.<ConnectAsync>d__31.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
Date: 06/08/2024 09:42:17 UTC
Bot Version: v1.11.5
---------------

---------------
Exception: System.Net.WebException
Message: 无法连接到远程服务器
Stack trace: 在 System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   在 System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
Date: 06/08/2024 09:42:17 UTC
Bot Version: v1.11.5
---------------

**Comment by egebilecen** [comment]
Hmm, yeah. The same error. I am out of ideas unfortunately.

**Comment by aayorishy** [comment]
> Hmm, yeah. The same error. I am out of ideas unfortunately.

its fine,
