### ISSUE TITLE
[BUG] READ COMMANDS IN DISCORD CHANNEL

### ISSUE THREAD

**Issue by MaximusPT** [egebilecen/PZServerDiscordBot#164]
Hello goodnight,

First of all, I want to congratulate you on the BOT, it's phenomenal!!

Now, since this last update v1. 11.5 has stopped reading the commands that we wrote in the chat channel.. 

Can you check what could be happening?

Thank you and good work!!

**Comment by egebilecen** [comment]
Hey, there have been no change to how commands are handled in the new version. Please be sure to check [intents](https://github.com/egebilecen/PZServerDiscordBot#warning) are properly configured. If there is no problem with the intents, I highly believe it is due to channel permissions. 😊

**Comment by MaximusPT** [comment]
Hi,

I solve it.. problem was the discord token was expired.. :/ :/ go figure ....

Thank you againd!! Excelent JOB!!
