### ISSUE TITLE
[BUG] Not adding new bot?

### ISSUE THREAD

**Issue by coolcat97** [egebilecen/PZServerDiscordBot#167]
![Screenshot 2024-09-08 204352](https://github.com/user-attachments/assets/c5d913ed-a610-49ed-9270-d3373698ff4b)

**Comment by coolcat97** [comment]
I have pasted my token into this file: 
![Screenshot 2024-09-08 204436](https://github.com/user-attachments/assets/44fc385f-da3c-4075-a6a7-55db702bdefd)

**Comment by coolcat97** [comment]
I'm a tard..... I took off the .txt and fixed it LOL

**Comment by egebilecen** [comment]
> I'm a tard..... I took off the .txt and fixed it LOL

Hey, Windows adds the ".txt" extension behind the scenes unless you activated the option to explicitly display file extensions. So in your case, the actual file name was `bot_token.txt.txt`. I am glad you figured it out! 😊
