### ISSUE TITLE
[BUG] The server won't boot.  

### ISSUE THREAD

**Issue by darkorgame** [egebilecen/PZServerDiscordBot#170]
The server starts correctly but I think there is a failure at the time of reading the mods, when I try to enter the server I get in public and everything is correct but when I enter it tells me that it has not been able to connect and the connection has been lost and I miss error number 1. 
in the file that is added PZserver in the last line 37 comes user.home.
in my files is in users.dymo could that be the flaw? 
![Screenshot_20241014_094048_Microsoft Remote Desktop](https://github.com/user-attachments/assets/1aa4dfb9-577e-40c2-adb0-cb6dd56d6a0f)
![Screenshot_20241014_094247_Microsoft Remote Desktop](https://github.com/user-attachments/assets/ffcbf730-abdd-4195-ac4c-7b5dc9930cc1)
![Screenshot_20241014_094239_Microsoft Remote Desktop](https://github.com/user-attachments/assets/afddbecb-1cd2-4ba2-999c-c8bc2b38be05)

**Comment by egebilecen** [comment]
Hey, I do not think the error you are getting during connecting to the server is related to the server.

> in the file that is added PZserver in the last line 37 comes user.home.

It only checks if `user.home` exist in the command. So it's irrelevant. I would say your problem is related to your network configuration than the bot problem.

**Comment by darkorgame** [comment]
Since I put the bot does not read me any mod, the problem has to come from the bot if or if, the server starts everything correct or the mods of the server if it reads what is not able to read the mods of the client.

**Comment by egebilecen** [comment]
> Since I put the bot does not read me any mod, the problem has to come from the bot if or if, the server starts everything correct or the mods of the server if it reads what is not able to read the mods of the client. The files you read from Zomboid are from User.Home but my directory is Users.Dymo where my Zomboid folder is.

`User.home` is only used to read some server files. However, it is not related to the error you are having. Bot only does run the existing .bat file to start the server then send commands to it. The error you are having while connecting to the server is not related to the bot.
