### ISSUE TITLE
[LOCALIZATION] Vietnamese

### ISSUE THREAD

**Issue by Trum00thay** [egebilecen/PZServerDiscordBot#172]
**Translated language's name in English:**
Vietnamese 

**How is the translated language written in the translated language?**
Tiếng Việt

**A brief description of the translation in the translated language:**
Bản dịch được dịch bởi Trum00thay. Chúc các bạn chơi game vui vẻ

*Do not forget to attach the zip file that contains the translation.*
[Vietnamese.zip](https://github.com/user-attachments/files/18001631/Vietnamese.zip)

**Comment by egebilecen** [comment]
Thank you very much for your contribution. Its added. Should be available in `!localization` command in max. 15 minutes.
