### ISSUE TITLE
Bot won't listen to any commands in discord?

### ISSUE THREAD

**Issue by Kraket91** [egebilecen/PZServerDiscordBot#19]
I have tried your 2 previous versions and got it to work, but after trying to update to 1.2.4 it wont listen to any commands at all. So I tried to redo the whole thing and need to set command, log and public channels but no reactions from the bot at all. I have followed the guide and took the files from the Release-v1.2.4 map and the PZServerDiscordBot-main map and placed it in the dedicated server directory. Am I stupid or whats going on? The bot is online and have premissions to every channel also.

**Comment by egebilecen** [comment]
Hey there. Please head to discord developer portal (which is the place you did set up your bot) and be sure that all bot intentions are enabled. Let me know whether it fixes.

![](https://i.ibb.co/PCjJzRG/Screenshot-6.png)

**Comment by Kraket91** [comment]
Thank you! That fixed it for me! :)

**Comment by egebilecen** [comment]
You are welcome. I will add this step to the README as well, hopefully. :)

**Comment by Kraket91** [comment]
That would be nice! But atleast people with the same problem can see this thread. :)
