### ISSUE TITLE
Mod Checker Not Working

### ISSUE THREAD

**Issue by saro8802** [egebilecen/PZServerDiscordBot#20]
Hi, ty for the bot. Atm im using the bot on a dedicated server (windows based) the mod checker is not working we got a mod update but not check came up, i waited 2 circle of setted time, in my case was every 30 minutes. Afetr 1 hour i setted at 5 minutes but anything. Let me know how to help. Maybe if you can put a command to activate this restart could be more easy to find the problem. ty

**Comment by egebilecen** [comment]
Hey there. There should be a `pzbot.log` file in the same folder as bot's. Please send it as an attachment. Also, if the mod that is updated either unlisted or private, bot won't detect it. Other than that, I need to check the log file. Also be sure bot has access / permissions in the log channel.

**Comment by saro8802** [comment]
Hi, confirm all mod are public, and bot has access to bot channel. I upload the log.
[pzbot.log](https://github.com/egebilecen/PZServerDiscordBot/files/9811119/pzbot.log)

**Comment by egebilecen** [comment]
Ah, okay. So issue with your server is, it isn't located in default server folder which is `C:\Users\<username>\Zomboid\Server`. Because of this, bot can't find the workshop mod list used in your server. Can you send me your `server.bat` file? I have an open issue to check alternative server folder by parsing it's content. I will try to implement it in few days. I want to check if it's the same case for you as well.

**Comment by saro8802** [comment]
Yeah, i did move my install folder in (D:) i upload the bat. ty
[server bat.zip](https://github.com/egebilecen/PZServerDiscordBot/files/9811237/server.bat.zip)

**Comment by egebilecen** [comment]
Thank you. I will fix this issue today or tomorrow!

**Comment by saro8802** [comment]
Nice, tyvmuch! ;)

**Comment by egebilecen** [comment]
Hey! [v1.2.5-beta](https://github.com/egebilecen/PZServerDiscordBot/releases/tag/v1.2.5-beta), I have added the future for supporting updated server locations. Can you check it out and confirm it is working?

**Comment by saro8802** [comment]
Sure, testing now.

**Comment by egebilecen** [comment]
Hmm. Sorry for the inconvenience. Will try to debug the problem.

**Comment by egebilecen** [comment]
Found the issue, fixing it now. Will soon re-release the v1.2.5-beta version.

**Comment by egebilecen** [comment]
[v1.2.5-beta-2](https://github.com/egebilecen/PZServerDiscordBot/releases/tag/v1.2.5-beta-2) Please give this a try! I hope I didn't mess up something again, haha.

**Comment by saro8802** [comment]
i'm using windows defender, i did download with another pc and tested the file on antivirus, nothing detected, idk why my first pc is blocking this...

**Comment by saro8802** [comment]
Ok so, i did upload the new version, atm i'm not getting any error, rn i can't upgrade one of my mods to trigger the bot cause im not at home, but as soon when it happens i'll let you know. ty

**Comment by egebilecen** [comment]
Thank you!

**Comment by saro8802** [comment]
not related issue, the bot is telling me to upload to version 1.2.4 cause im currently on the 1.2.5 XD, maybe it's cause is beta? idk

**Comment by egebilecen** [comment]
Don't worry about that. Version checking system isn't too advanced, haha. If it is older than your version, you can safely ignore. Especially for betas.

**Comment by saro8802** [comment]
So, we got an update and the bot seems to be worked as planned! :D let me know if you need some other tests. ty

**Comment by saro8802** [comment]
Question: is there some way to have a log of what mods did upgrade? So to be able to know what eventually broke the server or just to go check the new updates on steam? ty

**Comment by saro8802** [comment]
I see your point, generally speaking you know some other ways to get this information? Not related to your bot. ty

**Comment by egebilecen** [comment]
No idea to be honest. I never managed server myself. :(
