### ISSUE TITLE
Mods update

### ISSUE THREAD

**Issue by 6--** [egebilecen/PZServerDiscordBot#3]
Thanks a lot for this great bot!

Can you please give us the option to make the bot check for mods updates?
- check for updates every x s/m/h
- notify in-game & discord about the update
- restart the server after x s/m/h and notify countdown in-game & discord

https://github.com/JonnyPtn/zomboi/issues/37

Will be all-in-one bot!

Thank you again!

**Comment by egebilecen** [comment]
I hope you liked the bot in overall. Checking workshop in specified interval for mod updates and restarting server sounds pretty cool. I will look into that to see if it is feasible. I haven’t checked if Steam offers any API for workshop. At worse, mod workshop page can be parsed to extract information.

**Comment by egebilecen** [comment]
Okay. steam has an WEB API ([link](https://github.com/egebilecen/PZServerDiscordBot/blob/v1.1.0/src/SteamWebAPI.cs) for my 
 C# implementation) where I can fetch workshop item details. Started to work on the feature in `v1.1.0` branch.

**Comment by egebilecen** [comment]
Just performing last tests. Then I will release it as beta to allow people testing it extensively.
![](https://i.ibb.co/2g82vFS/Screenshot-1.png)

**Comment by egebilecen** [comment]
I have published the new beta release, [Release v1.1.0-Beta](https://github.com/egebilecen/PZServerDiscordBot/releases/tag/v1.1.x-Beta). Let me know if you find any issues. I will keep this issue open for a few days before closing.

**Comment by 6--** [comment]
Thanks a lot!
I have opened a ticket with the server provider and hopefully they will be able to add it to my server (they have a custom game panel)
Is there a way to donate/tip you for this great work?

**Comment by egebilecen** [comment]
You are welcome. You can tip me through [BuyMeACoffee](https://www.buymeacoffee.com/egebilecen). I hope you won't have any issues with the server provider about it.

**Comment by 6--** [comment]
do you have a https://ko-fi.com/ by any chance?
the BuyMeACoffee website doesn't accept PayPal :(

**Comment by egebilecen** [comment]
Unfortunately. ko-fi was unable to send funds to my country :(
