### ISSUE TITLE
restart at specific time

### ISSUE THREAD

**Issue by 6--** [egebilecen/PZServerDiscordBot#33]
Hi,

Is it possible to change auto restarts to a specific time?

example:
Restart at 1am, 7am, 1pm and 7pm

Thanks

**Comment by Jarlisk** [comment]
upvote on this feature

**Comment by egebilecen** [comment]
Hey all. So, I have been pondering on this feature for a while but unfortunately I will need to skip this feature. Adding this feature along with the existing restart interval feature will just complicate the whole process to manage server restarts.
