### ISSUE TITLE
!initiate_shutdown

### ISSUE THREAD

**Issue by 6--** [egebilecen/PZServerDiscordBot#39]
Hello, thank you for maintaining and adding new features to the bot

A !initiate_shutdown / !abort_shutdown will be a perfect commands for updating the server or adding a new mod

**Comment by egebilecen** [comment]
I will go ahead and deny this feature as I don't think it is `must have` and it's kinda tricky to implement in current system without changing restart schedule itself as I would be needed to add checks to see if a shutdown was initiated and close the server accordingly.
