### ISSUE TITLE
Translation - Can't compile the source correctly

### ISSUE THREAD

**Issue by X2yy** [egebilecen/PZServerDiscordBot#40]
When the project has compiled, the .exe is just a black screen, the server doesn't exec neither bot.

**Comment by X2yy** [comment]
![image](https://user-images.githubusercontent.com/93108700/205008641-638b5ad4-e321-4b7d-a23d-3c87524dfc71.png)

**Comment by egebilecen** [comment]
Hey, source code is compiled succesfully, actually. Check `pzbot.log` file. You will probably see some messages like this:

```[01.12.2022 09:44:31 UTC]BotUtility.NotifyLatestBotVersion() - commandChannel is null.```

And if you check your discord channel, you should see bot instructing you about setup: (If last created channel is visible to bot, that is. Otherwise bot won't send messages)

![Screenshot_1](https://user-images.githubusercontent.com/29331682/205020464-aae35316-33d0-4405-9b21-142b721ad214.png)

But maybe I should add a message to console that saying bot is running.

**Comment by X2yy** [comment]
ooh, those messages haven't showed up to me
when i type the command to create the channels i get the message that the bot is not configured yet.

**Comment by X2yy** [comment]
and yeah, the pzlogs show me that

**Comment by egebilecen** [comment]
Yeah, I borked up something in recent versions. It currently doesn't respond to those setup commands. I will try to fix it immediately. Thanks for the report!

**Comment by X2yy** [comment]
np, thank you

**Comment by egebilecen** [comment]
> np, thank you

*facepalms* Sorry, I just checked out and there isn't any issue with setup commands.

![image](https://user-images.githubusercontent.com/29331682/205029499-f17b839b-bc66-4c1c-b287-7feb391dc4e7.png)
Try to use the command like this. Tag a channel you want bot to work in.
If bot doesn't respond, that means bot has no access to channel that you just sent your message.

**Comment by egebilecen** [comment]
By the way, I added some warning messages onto console as well. Just in case of someone builds the source code themselves and try to test some stuff. It will be added with the release of `v1.8.0`.

**Comment by X2yy** [comment]
hmm i tried but nothing, when i turn on the bot the command channel back to "0" in config.

**Comment by X2yy** [comment]
and just give me a black screen, the server don't turn on

**Comment by X2yy** [comment]
just the bot, not like the compiled version

**Comment by X2yy** [comment]
![image](https://user-images.githubusercontent.com/93108700/205031547-a20d5331-e12a-4c1c-b8ae-2e91c735e78d.png)

**Comment by egebilecen** [comment]
It seems like you able to configure public and log channels but command channel. Try to run `!set_command_channel` in one of those channels.

**Comment by X2yy** [comment]
same error, i ran in a public channel.
"the bot isn't configured yet"

**Comment by X2yy** [comment]
ps: i just made a translations change in source

**Comment by egebilecen** [comment]
Translation shouldn't create any problem. Procedure follows as: 
![Screenshot_1](https://user-images.githubusercontent.com/29331682/205033214-07abe4d1-cc37-4ee6-a381-610b0ceb8453.png)

If bot doesn't respond with any reaction, it means it doesn't receive the command at all.

**Comment by X2yy** [comment]
yeah, the bot responds with a "x" reaction

**Comment by egebilecen** [comment]
Does it respond with any message?

**Comment by X2yy** [comment]
when i use the command to define the command channel etc

**Comment by egebilecen** [comment]
Can you send me screenshot of the channel? With your messages visible.

**Comment by X2yy** [comment]
![image](https://user-images.githubusercontent.com/93108700/205034109-64bc7673-bad4-42c2-8040-2fd396db224a.png)

**Comment by egebilecen** [comment]
Okay, there is a check going on with fails because of translation. These checks are done in `CommandHandler.cs`. You might want to take a look at it.

**Comment by X2yy** [comment]
![image](https://user-images.githubusercontent.com/93108700/205034548-ac8fc41e-7c1c-4059-b528-355ce0fea671.png)

**Comment by egebilecen** [comment]
Did you change any translation in `CommandHandler.cs` line 122?

This is the original line:
```
else if(!isBotConfigured && commandModule != "BotCommands")
```

**Comment by X2yy** [comment]
yes i do maybe i messed the source...
let me try compile without changes

**Comment by egebilecen** [comment]
there shouldn't be any problem as long as file names aren't changed or class names

**Comment by X2yy** [comment]
i need to start the bot and the start.bat?
or the exe does both?

**Comment by X2yy** [comment]
worked i messed the class names.
one more question
how can i make the bot work with pz?

**Comment by egebilecen** [comment]
> worked i messed the class names. one more question how can i make the bot work with pz?

First, you need to build (&run) it in release configuration. Second, just follow the steps in `README.md` and you are good to do.

**Comment by X2yy** [comment]
Nice.
It worked, thanks for you time!

**Comment by egebilecen** [comment]
> Nice. It worked, thanks for you time!

You are welcome, good luck! :)

**Comment by egebilecen** [comment]
Hey there, I am planning to add a localization system which will allow people to easily change the command names, their descriptions, bot responses etc. to their own language. My plan is to add this feature with `v1.8.0` along with auto-update system. No release date though so I am just writing this to give a heads up :)
