### ISSUE TITLE
Anlık Perk bilgisi - Sunucuya giriş/çıkış bilgisi - ölüm bilgisi

### ISSUE THREAD

**Issue by mounti03** [egebilecen/PZServerDiscordBot#41]
1-Bir Kanal belirlenip sunucuda oynayan kişi bir yetenek seviyesi kazandığında o kanala bilgisini geçebilir.
2-Anlık perk bilgisi ile aynı kanal da biri ölünce ''xxx kullanıcı xx gün hayat da kaldı ve öldü'' gibi bir yazı yazabilir
3-Yine aynı kanal da biri sunucuya girdiğinde ''xxx Sunucuya giriş yaptı xx gündür yaşıyor'' gibi bir yazı yazabilir

Bu özellikler eklenirse çok tatlı olabilir başka bir sunucu da gördüğüm örnekleri bırakıyorum.

![Screenshot_2](https://user-images.githubusercontent.com/71854023/208192381-091ac8f2-631e-4b54-8cb1-a16958666bdf.png)
![Screenshot_4](https://user-images.githubusercontent.com/71854023/208192384-67535eb6-6391-4d41-a68d-097946347ffd.png)
![Screenshot_5](https://user-images.githubusercontent.com/71854023/208192387-6d2de5bf-548b-4d0d-bc8d-c967de25680a.png)

**Comment by egebilecen** [comment]
Merhaba, bu özellikler yapılacak listemde.

**Comment by mounti03** [comment]
!server_msg Komutun da cümle de boşluk olursa The input text has too many parameters. uyarısı veriyor bunu düzeltebilir misiniz

**Comment by egebilecen** [comment]
> !server_msg Komutun da cümle de boşluk olursa ''The input text has too many parameters.'' uyarısı veriyor bunu düzeltebilir misiniz

`!help` komutu ile örnek kullanımları açıklamaların yanında görebilirsin. O komutu `!server_msg “Örnek mesaj”` şeklinde kullanman gerekiyor. Komutta herhangi bir hata bulunmamakta.
