### ISSUE TITLE
WorkshopItemUpdateChecker Error

### ISSUE THREAD

**Issue by mounti03** [egebilecen/PZServerDiscordBot#42]
![Screenshot_6](https://user-images.githubusercontent.com/71854023/208193394-7ffbb05c-ea67-4364-90bb-2a413d43fc69.png)

**Comment by egebilecen** [comment]
Merhaba, botun bütün kanallara yazma erişimi olduğundan emin olur musun? Şuanki log kaydından maalesef bir şey anlaşılmıyor, bu kısımdaki log kaydını bir sonraki versiyonda iyileştireceğim. Bir sonraki versiyon ile tekrar kontrol edelim eğer devam ederse.

**Comment by mounti03** [comment]
tamamdır

**Comment by egebilecen** [comment]
Merhaba, yeni güncelleme yayınlandı. Yeni versiyonda botu çalıştırıp hayla hata alıp almadığını kontrol eder misin? Hata alırsanda log dosyasını ekte gönderir misin? Teşekkürler. Ayrıca dil sistemini de ekledim, `README.md` dosyasından detayları bulabilirsin.
