### ISSUE TITLE
Çeviri problemi

### ISSUE THREAD

**Issue by ali98bayram** [egebilecen/PZServerDiscordBot#44]
Merhaba localization/default.json dosyasını türkçe çevirisini gerçekleştirip kaydettim ancak botun çevirisi gerçekleşmiyor halen ingilizce şekilde çalışıyor v1.7 dosyalarını v1.8 üzerinemi atmam gerekiyor yeni kurulum nasıl oluyor kafam karıştı yardımcı olursanız çok sevinirim teşekkürler...

**Comment by ali98bayram** [comment]
Türkçe karakterler kullanabilirmiyiz ö ç ğ ş gibi?

**Comment by egebilecen** [comment]
Evet, sorun olmaması gerekiyor. Sorun olursa zaten güncellerim.

**Comment by ali98bayram** [comment]
[TR.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10262686/TR.zip)

**Comment by egebilecen** [comment]
Bu dosyayı nereden düzenledin? Bir çok kısımda bozulmalar olmuş.

**Comment by ali98bayram** [comment]
Notepad ++

**Comment by egebilecen** [comment]
Anladim, düzenlemeden sonra [buradan](https://jsonformatter.curiousconcept.com/) hataları kontrol eder misin. Şuan sebebini bilmediğim bir şekilde bütün yazıların formatı bozulmuş. `UTF-8` olarak düzenlediğinden emin olur musun. Şuan hatalı bir durumda olduğu için kabul edemiyorum.

**Comment by ali98bayram** [comment]
[tr.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10262887/tr.zip)
Tekrar denermisin hocam not defteri ile kaydettim

**Comment by egebilecen** [comment]
Tamamdır bir problem gözükmüyor. Sanırım translate çevirisi yapılmış? :)

**Comment by ali98bayram** [comment]
Yarı yarıya diyebiliriz ellemek istemedim çoğu yerine kendim uydurmak istemedim bazı kelimeleri

**Comment by egebilecen** [comment]
Tamamdır, şimdi ekliyorum.

**Comment by egebilecen** [comment]
Ekledim, 15 dakikaya `!localization` komutunda gözükür.

**Comment by egebilecen** [comment]
Şimdi kontrol ettim de çeviri dosyası hatalı olduğu için hata verecek bot. Senin el ile teker teker bütün tırnak işaretlerinin arasını doldurman gerekiyor gibi gözüküyor :)

**Comment by ali98bayram** [comment]
Boşlukmu bırakmam gerekiyor başı ve sonuna ben onları silmiştim bu arada !localization Türkçe yazınca komutu kabul etmiyor

**Comment by ali98bayram** [comment]
[TR.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10263100/TR.zip)
Attığınız sitede bu hata vermiyor bu arada tekrar denermisiniz rica etsem

**Comment by egebilecen** [comment]
Otomatik formatlattim internetten. Turkce karakterleri kaldirip Ingilizce yapti ama yapacak bir sey yok artik :)

**Comment by ali98bayram** [comment]
Verdim üstadım teşekkürler herşey için

**Comment by egebilecen** [comment]
Rica ederim. Ben de şimdi kontrol ettim, Türkçe karakter sıkıntısı var. Onunla ilgileneceğim ilerleyen zamanlarda. Ama onun harici sorunsuzca çalışmakta.
