### ISSUE TITLE
New Issue Starting

### ISSUE THREAD

**Issue by saro8802** [egebilecen/PZServerDiscordBot#51]
Hi man :) i'm getting this error with a new bot, it's important?

---------------
Exception: System.Exception
Message: WebSocket connection was closed
Stack trace: in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Discord.ConnectionManager.<WaitAsync>d__34.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   in Discord.WebSocket.DiscordSocketClient.<OnConnectingAsync>d__114.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Discord.ConnectionManager.<ConnectAsync>d__31.MoveNext()
--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---
   in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext()
Date: 30/12/2022 12:38:20 UTC
Bot Version: v1.8.1
---------------

---------------
Exception: Discord.Net.WebSocketClosedException
Message: The server sent close 4014: "Disallowed intent(s)."
Stack trace: in Discord.Net.WebSockets.DefaultWebSocketClient.<RunAsync>d__34.MoveNext()
Date: 30/12/2022 12:38:20 UTC
Bot Version: v1.8.1
---------------

**Comment by egebilecen** [comment]
Hey!
Did you enable all intents in Discord developer portal? You can find the details in the notes of [this ](https://github.com/egebilecen/PZServerDiscordBot#installing-bot-files) section.

**Comment by saro8802** [comment]
omg XD you answered too fast ahahha, yes already found and fixed :) ty

**Comment by egebilecen** [comment]
> omg XD you answered too fast ahahha, yes already found and fixed :) ty

No problem. I just happen to be on the computer and received an email, haha.
