### ISSUE TITLE
nedenini anlamadığım hata

### ISSUE THREAD

**Issue by mounti03** [egebilecen/PZServerDiscordBot#52]
![image](https://user-images.githubusercontent.com/71854023/210244803-b46cb24d-2add-4d5d-9daf-4b4535e1e1f7.png)

Birşey Yapmama rağmen sürekli böyle oluyor
![Screenshot_9](https://user-images.githubusercontent.com/71854023/210244895-ac099d2f-7e88-458d-8741-61fe997cc872.png)

**Comment by egebilecen** [comment]
Merhaba,

Steam web API'sine gönderilen isteğe yanıt gelmemesinden kaynaklı bir hatanın loglarını görmekteyim. Sunucunuzun IP adresi Steam tarafından kara listeye alınmış olabilir.

**Comment by mounti03** [comment]
Sunucuyu dün aldım neden böyle bir şey olsun ki

**Comment by egebilecen** [comment]
> Sunucuyu dün aldım neden böyle bir şey olsun ki

Bilmiyorum maalesef. Zaten problem sunucunun kendi ile değil, sunucunun kullandığı internet servis sağlayıcısı ile ilgilidir. Belki de sunucu firewall’ı bir engelleme yapıyordur bilemiyorum.
