### ISSUE TITLE
Localization of <portuguese>

### ISSUE THREAD

**Issue by Paz0s** [egebilecen/PZServerDiscordBot#53]
[portuguese.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10366071/portuguese.zip)

**Comment by egebilecen** [comment]
Hey, thank you for sharing your Portugese translation! Could you tell me how Portugese written in your language? So I can add it without using English word for Portugese. Also a brief description about translation in your own language would be appreciated. Something like "Portugese translation of the bot." in Portugese or something like that.

**Comment by Paz0s** [comment]
So, just to explain: we have 2 types of portuguese: European Portuguese (from Portugal) and Brazilian Portuguese (from Brazil)

I translated it into Brazilian Portuguese. They are extremely similar languages.

Portuguese = PTBR - Português brasileiro
Description = Tradução do bot para Português do Brasil.

**Comment by egebilecen** [comment]
I see, thank you! I have added the translation. It should appear in `!localization` in 10 minutes if there is a recent cache.

**Comment by egebilecen** [comment]
Be sure to use command like this: `!localization "Português Brasileiro"`
