### ISSUE TITLE
Localization of <korean>

### ISSUE THREAD

**Issue by jun1024** [egebilecen/PZServerDiscordBot#55]
[korean.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10419980/korean.zip)

**Comment by egebilecen** [comment]
Hey, thank you for sharing your Korean translation! Could you tell me how Korean written in your language? So I can add it without using English word for Korean. Also a brief description about translation in your own language would be appreciated. Something like "Korean translation of the bot." or something like that in Korean.

**Comment by jun1024** [comment]
Korean -> 한국어
It is Korean translation of the bot. -> 이 봇의 한국어 번역입니다.

sorry, I missed some letters so reupload revised one.
[korean.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10420022/korean.zip)

thank you for your hard work!

**Comment by egebilecen** [comment]
Thank you, I have added the translation. You can activate it by using `!localization 한국어` command! :)

**Comment by jun1024** [comment]
Nice, It works perfectly!
I have a suggestion about new feature, can you make a command for checking current user number? I used to type 'players' in startserver64.bat cmd, but I can't type it in cmd anymore with your bot. so It would be great if you add a checking player number command which I can use in discord channel.

**Comment by egebilecen** [comment]
> Nice, It works perfectly!
Good to hear that! :)

> I have a suggestion about new feature, can you make a command for checking current user number?
Yes, could you create a separate issue with appropriate title? (I am not sure when I can get to it though, been quite busy lately)
