### ISSUE TITLE
korean localization update

### ISSUE THREAD

**Issue by jun1024** [egebilecen/PZServerDiscordBot#61]
I found some mistakes in my last korean translation.
so I upload this modified version, please update it when you are not busy. thanks.
[korean.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10473493/korean.zip)

**Comment by egebilecen** [comment]
Hey, thank you. I will update it. You will get a notification in bot command channel when new version of localization available.

**Comment by egebilecen** [comment]
Okay, it's updated. You should get new version notice in a bit.
