### ISSUE TITLE
Localization of <language here>

### ISSUE THREAD

**Issue by KirenSilver** [egebilecen/PZServerDiscordBot#65]
[RU.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10646401/RU.zip)

**Comment by egebilecen** [comment]
Hey, thank you for sharing your Russian translation! Could you tell me how Russian written in your language? So I can add it without using English word for Russian. Also a brief description about translation in your own language would be appreciated. Something like "Russian translation of the bot." or something like that in Russian.

**Comment by KirenSilver** [comment]
Could you tell me how Russian written in your language? Русский язык. Описание.  Русский перевод Бота

**Comment by KirenSilver** [comment]
Добрый день прошу помогите с переводом. Бот не видит мой перевод. Уже перепробовал много путей куда положить ru.json пока перевести мне не удалось(

**Comment by egebilecen** [comment]
I haven't added it yet. Will write a comment when I add it

**Comment by KirenSilver** [comment]
хорошо, спасибо

**Comment by egebilecen** [comment]
It's added. You seem to made some mistakes while translating the file. Especially the special keywords. You need to fix them.

**Comment by KirenSilver** [comment]
хорошо сейчас посмотрю

**Comment by KirenSilver** [comment]
[RU.zip](https://github.com/egebilecen/PZServerDiscordBot/files/10660483/RU.zip)

**Comment by KirenSilver** [comment]
Скажите пожалуйста что мне нужно сделать чтобы перевод заработал? у меня ни как не получается это сделать.
Please tell me what I need to do to make the transfer work? I have no way to do it.

**Comment by egebilecen** [comment]
I will leave a comment when I update it.

**Comment by egebilecen** [comment]
You still have issues with special words in this translation. Please fix them. For example: `{минуты}`.

**Comment by KirenSilver** [comment]
Хорошо работаю над этим, это оказалось сложнее чем я думал)

**Comment by egebilecen** [comment]
I can't change bot to use `StartServer64` because there might be people who are using 32bit server. Also, please comment in English.
