### ISSUE TITLE
error when translating to Brazilian Portuguese

### ISSUE THREAD

**Issue by gabrielm3234** [egebilecen/PZServerDiscordBot#70]
when placing the command (!localization Português Brasileiro) that is right. but this appears (The input text has too many parameters.) I can put it in all the languages of the site but not this one.

**Comment by egebilecen** [comment]
Hey. Use with quotes: `!localization Português Brasileiro`

**Comment by gabrielm3234** [comment]
thanks. I was doing it like this (!localization "<localization name>") because it appears like this as an example.
thanks.
