### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ledinhvu2626** [egebilecen/PZServerDiscordBot#78]
![received_156582370674740~2.jpg](https://user-images.githubusercontent.com/95129518/236598930-7e0b8717-65ee-496d-ae02-509d05f08193.jpg)

Hey love your work man, but i have this error me and my friend are really frustrated with it can you help us.

**Comment by egebilecen** [comment]
Hello, could you please attached the log file?

**Comment by egebilecen** [comment]
Hello, could you please attach the log file?

**Comment by egebilecen** [comment]
By just judging from the console error, you did skip the [4. article](https://github.com/egebilecen/PZServerDiscordBot#installing-bot-files) in `Installing Bot Files` section.

**Comment by egebilecen** [comment]
Hello,
By just judging from the console error, you did skip the [4. article](https://github.com/egebilecen/PZServerDiscordBot#installing-bot-files) in `Installing Bot Files` section.
