### ISSUE TITLE
the bot is deconfigured for some reason

### ISSUE THREAD

**Issue by PentSec** [egebilecen/PZServerDiscordBot#79]
Hello, after working for several hours with the bot configured, suddenly and without warning it gets disconfigured and the command channel id is set to 0. thus having to reconfigure the bot to make it work. any solution? as a small note I leave, that I do not edit the channels or delete them or anything since this is happening to me.

> {
>   "GuildId": 639228542076321812,
>   **"CommandChannelId": 0,**
>   "LogChannelId": 1102723611929882654,
>   "PublicChannelId": 1102723611929882654,
>   "ServerLogParserSettings": {
>     "PerkParserCacheDuration": 10
>   },
>   "ServerScheduleSettings": {
>     "ServerRestartSchedule": 21600000,
>     "WorkshopItemUpdateSchedule": 600000,
>     "WorkshopItemUpdateRestartTimer": 900000
>   },
>   "BotFeatureSettings": {
>     "AutoServerStart": false,
>     "NonPublicModLogging": false
>   },
>   "LocalizationInfo": null
> }

**Comment by egebilecen** [comment]
Hey. Maybe a crash or sudden restart happened in your machine thus changes did not save? It could be due to some Discord related error as well.

**Comment by PentSec** [comment]
I set up the bot and start using the commands and suddenly without warning I put a command and it tells me that the bot is not configured I go to the folder and check and the channel ID has been set to 0. but it is always that channel the command channel. maybe I should try another channel. or delete that one and create another one.
