### ISSUE TITLE
 question about executable

### ISSUE THREAD

**Issue by ornn2k** [egebilecen/PZServerDiscordBot#81]
Hi,

Is there any way that it is possible to allow triggering manual command input at the .exe prompt?

Example

I want to type some native PZ command directly into the executable itself.

Is there such a possibility?

**Comment by egebilecen** [comment]
Hey, if you mean typing commands to console, you can use `!server_cmd` command. Check the readme for more details.

**Comment by egebilecen** [comment]
I will try to update the bot and make it listen the commands from other bots as well. I should be updated the bot tomorrow.
