### ISSUE TITLE
Localization of latino

### ISSUE THREAD

**Issue by Starklzl** [egebilecen/PZServerDiscordBot#83]
{
  "gen_enab_up": "Habilitado",
  "gen_disa_up": "Deshabilitado",
  "gen_hours_text": "hora(s)",
  "gen_minutes_text": "minuto(s)",
  "gen_past_rel_time_one_sec": "hace un segundo",
  "gen_past_rel_time_secs": "Hace {seconds} segundos ",
  "gen_past_rel_time_one_min": "hace un minuto",
  "gen_past_rel_time_mins": "hace {minutes} minutos",
  "gen_past_rel_time_one_hour": "hace una hora",
  "gen_past_rel_time_hours": "hace {hours} horas",
  "gen_past_rel_time_yest": "ayer",
  "gen_past_rel_time_days": "hace {days} días",
  "gen_past_rel_time_one_month": "hace un mes",
  "gen_past_rel_time_months": "hace {months} meses ",
  "gen_past_rel_time_one_year": "hace un año",
  "gen_past_rel_time_years": "hace {years} años ",
  "gen_no_desc": "No hay descripción disponible",
  "gen_last_cache_text": "El último caché fue a las **{relative_time}**.",
  "bot_disc_chan_set_ok": "Canal  <#{channel_id}> configurado correctamente para que funcione el bot.",
  "warn_debug_mode": "ADVERTENCIA: el bot se está ejecutando en la configuración DEBUG.",
  "warn_console_missing_conf": "Al bot le falta la configuración. Consulte {repo_url}#bot-configuration.",
  "warn_server_not_running": "El servidor no se está ejecutando.",
  "warn_bot_conf_not_done": "La configuración del bot aún no se ha realizado.",
  "warn_bot_conf_cmd_chan": "Configura un canal para que el bot funcione usando el comando **!set_command_channel <channel tag>** command.",
  "warn_bot_conf_log_chan": "Configura un canal para que el bot escriba registros usando el comando **!set_log_channel <channel tag>** command.",
  "warn_bot_conf_pub_chan": "Configura un canal para que el bot acepte comandos en un canal público usando el comando **!set_public_channel <channel tag>** command.",
  "warn_bot_wont_accept_cmd": "Bot won't accept any other commands until the steps above step(s) are completed. @everyone",
  "warn_unknown_cmd": "Unknown command.",
  "err_bot_token": "Couldn't retrieve bot token from \"bot_token.txt\" file.\nPlease refer to \"{repo_url}#writing-the-discord-bot-token-into-file\".",
  "err_retv_bot_token": "An error occured while retrieving bot token. Error details are saved into {log_file} file.\nPlease refer to \"{repo_url}/issues\" and create an issue about this with the log file.",
  "err_serv_bat": "Couldn't find \"server.bat\" file in the folder. Please rename the bat file you were using to start the server as \"server.bat\". For example, if you were using \"StartServer64.bat\", rename it as \"server.bat\" without quotes.",
  "err_disc_auth_fail": "Authentication failed! Be sure your discord bot token is valid.",
  "err_disc_disconn": "An error occured and discord bot has been disconnected! Error details are saved into {log_file} file.\nPlease refer to \"{repo_url}/issues\" and create an issue about this with the log file.",
  "err_export_localization": "ERROR: no se pudo exportar el archivo de localización predeterminado!",
  "info_disc_act_bot_ver": "Bot Version: {version}",
  "info_bot_started": "Bot (**{version}**) is started. :zombie:",
  "info_bot_new_version": "There is a new version (**{new_version}**) of bot! Current version: **{current_version}**. Please consider to update from {repo_url}. If you enjoy the bot, please leave a :star: to repo if you haven't :relaxed:.",
  "info_bot_new_early_version": "There is a new **early access** version (**{new_version}**) of bot! Current version: **{current_version}**. This early access version can be downloaded from **Releases** section of the repo. Repo link: {repo_url}. This version may not be stable as it is not extensively tested (which I also have no means to test it as I don't own a server so any help is appreciated) but it offers early access to the new features. If any problem occurs, you can always switch back to old version from the **Releases** section. If you observe any problem, please report it in **Issues** section.",
  "info_export_localization": "INFORMACIÓN: la localización predeterminada se exportó correctamente!",
  "disc_cmd_help_user_cmds_title": "Aquí está la lista de comandos:",
  "disc_cmd_help_admin_cmds_title": "Lista de comandos de administración:",
  "disc_cmd_help_bot_cmds_title": "Lista de comandos de bots:",
  "disc_cmd_help_pzs_cmds_title": "Lista de comandos del servidor de Project Zomboid:",
  "disc_cmd_set_command_channel_warn": "Channel <#{channel_id}> is configured to be log channel. Please select a different channel.",
  "disc_cmd_set_log_channel_warn": "Channel <#{channel_id}> is configured to be command channel. Please select a different channel.",
  "disc_cmd_get_settings_serv_id": "**Server ID:** `{server_id}`",
  "disc_cmd_get_settings_cmd_chan_id": "**Command Channel ID:** `{channel_id}` (<#{channel_id}>)",
  "disc_cmd_get_settings_log_chan_id": "**Log Channel ID:** `{channel_id}` (<#{channel_id}>)",
  "disc_cmd_get_settings_pub_chan_id": "**Public Channel ID:** `{channel_id}` (<#{channel_id}>)",
  "disc_cmd_get_settings_perk_cac_dur": "**Perk Parser Cache Duration:** {minutes} minute(s)",
  "disc_cmd_get_settings_res_sch_int": "**Restart Schedule Interval:** {minutes} minute(s)",
  "disc_cmd_get_settings_mod_sch_int": "**Workshop Mod Update Checker Interval:** {minutes} minute(s)",
  "disc_cmd_get_settings_mod_rst_timer": "**Workshop Mod Update Restart Timer:** {minutes} minute(s)",
  "disc_cmd_get_settings_serv_aut_strt": "**Server Auto Start:** {state}",
  "disc_cmd_get_settings_mod_logging": "**Non-public Mod Logging:** {state}",
  "disc_cmd_get_schedules_run": "**{name}** schedule will run <t:{timestamp}:R>.",
  "disc_cmd_get_schedules_not_fnd": "No schedule found.",
  "disc_cmd_set_restart_interval_int_warn": "El intervalo de reinicio debe ser de al menos 60 minutos.",
  "disc_cmd_set_restart_interval_int_ok": "Server restart schedule is updated.",
  "disc_cmd_set_mod_update_check_interval_int_warn": "Interval minutes cannot be smaller than 0. But it can be 0 which means there won't be any workshop mod update checking.",
  "disc_cmd_set_mod_update_check_interval_int_ok": "Workshop mod update check schedule is updated.",
  "disc_cmd_set_mod_update_restart_timer_warn": "El intervalo debe ser de al menos 1 minuto.",
  "disc_cmd_set_mod_update_restart_timer_ok": "El temporizador de reinicio de actualización de mod de WorkShop se actualizo.",
  "disc_cmd_toggle_non_public_mod_logging_ok": "Non-public mod logging feature has been {state}.",
  "disc_cmd_set_perk_cache_duration_warn": "la duración no puede ser menor que 0. Pero puede ser 0, lo que significa que no habrá almacenamiento en caché.",
  "disc_cmd_set_perk_cache_duration_ok": "Se actualiza la duración del caché de ventajas.",
  "disc_cmd_reset_perk_cache_ok": "Se ha restablecido el caché de ventajas.",
  "disc_cmd_toggle_server_auto_start_ok": "La característica de inicio automático del servidor ha sido {state}.",
  "disc_cmd_backup_server_warn": "No se puede crear una copia de seguridad mientras el servidor se está ejecutando.",
  "disc_cmd_backup_server_ok": "Iniciando la copia de seguridad del servidor. Puede verificar el progreso de la copia de seguridad en el canal de registro (<#{channel_id}>).",
  "disc_cmd_backup_server_start": "Se inició la copia de seguridad del servidor. Total de **{folder_count} folder(s)** será respaldado.",
  "disc_cmd_backup_server_item_done": "Copia de seguridad de `{folder_name}` esta completado. **({remaining_folder_count} folder left)**",
  "disc_cmd_backup_server_finish": "Se completó la copia de seguridad del servidor!",
  "disc_cmd_localization_embed_title": "Información de localización actual",
  "disc_cmd_localization_embed_language": "Idioma",
  "disc_cmd_localization_embed_version": "Version",
  "disc_cmd_localization_embed_desc": "Descripción",
  "disc_cmd_localization_upd_ok": "La localización cambió con éxito a **{localization}** ({version}).",
  "disc_cmd_localization_upd_exception": "Se produjo un error desconocido al cambiar la localización!",
  "disc_cmd_localization_not_found": "no pude encontrar **{localization}** localización!",
  "disc_cmd_localization_download_fail": "¡No se pudo descargar la localización! Por favor, inténtelo de nuevo más tarde...",
  "disc_cmd_localization_update_text": "Hay una nueva versión para **{localization}** ({version})! Por favor use `!localization \"{localization}\"` comando para actualizar.",
  "disc_cmd_localization_avaib_list": "Lista de localizaciones disponibles:",
  "disc_cmd_localization_usage": "Por favor use `!localization \"<localization name>\"` comando para actualizar la localización actual. Puede restablecer la localización a los valores predeterminados utilizando `!localization default` comando.",
  "disc_cmd_localization_no_localization": "No hay otras localizaciones disponibles en este momento.",
  "disc_cmd_start_server_warn_running": "El servidor ya se está ejecutando.",
  "disc_cmd_start_server_warn_backup": "No se puede iniciar el servidor durante la copia de seguridad en curso. Espere hasta que finalice la copia de seguridad.",
  "disc_cmd_start_server_ok": "El servidor debe estar en camino de comenzar. Este proceso puede llevar un tiempo. Verifique el estado del servidor en 1 o 2 minuto(s).",
  "disc_cmd_stop_server_warn": "El servidor ya está parado.",
  "disc_cmd_restart_server_ok": "Reiniciando el servidor.",
  "disc_cmd_initiate_restart_warn_min": "Los minutos no pueden ser 0. Use `!restart_server` en cambio.",
  "disc_cmd_initiate_restart_info_server_msg": "Se ha iniciado un reinicio manual del servidor. El servidor se reiniciará en {minutes} minuto(s).",
  "disc_cmd_initiate_restart_info_disc_msg": "Se ha iniciado el reinicio manual. El servidor se reiniciará en **{minutes} minuto(s)**.",
  "disc_cmd_abort_restart_ok_server": "El próximo reinicio ha sido abortado. El próximo reinicio ocurrirá en {minutes} minutos.",
  "disc_cmd_abort_restart_ok_disc": "El próximo reinicio ha sido abortado.",
  "disc_cmd_perk_info_no_result": "No se pudo encontrar ningún registro de beneficios relacionado con el nombre de usuario **{username}**.",
  "disc_cmd_perk_info_result_title": "Información PERKS de **{username}**:",
  "disc_cmd_bot_info_text": "Este bot está escrito para que las personas administren fácilmente su servidor usando Discord. Se puede acceder al código fuente y a los archivos bot desde {repo_url}. Si disfruta del bot, deje una :star: para hacer un repositorio si no lo ha hecho :relaxed:.",
  "disc_cmd_server_status_running": "El servidor esta **ENCENDIDO** :hamster:",
  "disc_cmd_server_status_backup": "Actualmente el **server backup** está en proceso. :wrench:",
  "disc_cmd_server_status_dead": "El servidor esta **MUERTO** :skull:",
  "disc_cmd_restart_time_text": "El servidor se reiniciará <t:{timestamp}:R>.",
  "disc_cmd_game_date_warn_file": "No se pudo encontrar el archivo de tiempo.",
  "disc_cmd_game_date_response": "```Current in-game date: {day}/{month}/{year}```*(Date is in DD-MM-YYYY aka European format)*",
  "sch_name_serverrestart": "Reinicio del servidor",
  "sch_name_serverrestartannouncer": "Locutor de reinicio del servidor",
  "sch_name_workshopitemupdatechecker": "Comprobador de actualización de mod de WORKSHOP",
  "sch_name_autoserverstarter": "Iniciador de servidor automático",
  "sch_name_botnewversioncchecker": "Comprobador de nueva versión de bot",
  "sch_name_localizationnewversioncchecker": "Localization New Version Checker",
  "sch_autoserverstart_text": "**[Auto Server Starter]** l servidor no se está ejecutando. Intentando iniciar el servidor.",
  "sch_serverrestart_restart_text": "**[Server Restart Schedule]** Reiniciando el servidor.",
  "sch_serverrestart_server_not_running": "**[Server Restart Schedule]** Server is not running. Skipping...",
  "sch_serverrestartannouncer_text": "El servidor se reiniciará en {time_value} {time_text}.",
  "sch_workshopitemupdatechecker_details_fail": "**[Workshop Mod Update Checker]** Cannot get the details of mod with the ID of `{id}`. It is either set as unlisted or private in Steam Workshop. Steam doesn't allow getting details of unlisted/private workshop items so if it is updated, bot won't detect it. `(Result code: {code})`\n**Mod Link:** {link}",
  "sch_workshopitemupdatechecker_log_chan_text": "**[Workshop Mod Update Checker]** A workshop mod update has been detected. Preparing to restart server in {minutes} minute(s).",
  "sch_workshopitemupdatechecker_pub_chan_text": "**[Workshop Mod Update Checker]** A workshop mod update has been detected. Server will be restarted in {minutes} minute(s).",
  "sch_workshopitemupdatechecker_server_announcement_text": "Se ha detectado la actualización de un mod. El servidor se reiniciará en {minutes} minuto(s)."
}

**Comment by egebilecen** [comment]
Hey, thank you for sharing your translation! Please attach the translation file as a zip. Also, could you tell me how is your language written? So I can add it without using English word for it. Also a brief description about translation in your own language would be appreciated. Something like "<your language here> translation of the bot." or something like that in your language.
