### ISSUE TITLE
Localization of Spanish

### ISSUE THREAD

**Issue by Cevaconce** [egebilecen/PZServerDiscordBot#85]
[Español.zip](https://github.com/egebilecen/PZServerDiscordBot/files/12087979/Espanol.zip)
 
 - Spanish = Español
 
 - Desc: Traducción del bot al español.

Thnks 4 your bot <3

greatings.

**Comment by egebilecen** [comment]
Hey, thank you for sharing your Spanish translation! Could you tell me how Spanish written in your language? So I can add it without using English word for Spanish. Also a brief description about translation in your own language would be appreciated. Something like "Spanish translation of the bot." or something like that in Spanish.

**Comment by Cevaconce** [comment]
I already updated the post. 

There are some lines of text that I haven't had any interaction with yet, so I don't understand their context. If I notice that the translation needs some adjustments, is a future update possible?

**Comment by egebilecen** [comment]
Thanks for the update. And, yes. I can update it in the future.

**Comment by egebilecen** [comment]
I have merged the translation. It should appear on bot settings in about 15 minutes.

**Comment by Cevaconce** [comment]
Thnks so much <3

Evrything its ok at the moment.
