### ISSUE TITLE
Feature suggestion - specific restart times based on system clock

### ISSUE THREAD

**Issue by RemainQuenched** [egebilecen/PZServerDiscordBot#89]
Would be nice to be able to setup specific times the server restarts based on the system clock. The current method creates sporadic restart times.

**Comment by RemainQuenched** [comment]
Also, adding a set of commands to decide what you want the bot to log as well as the ability to log things like executed admin commands, player connections, updates for mods and what mods were updated in the bot log channel.

**Comment by DomicidalDesigns** [comment]
> Would be nice to be able to setup specific times the server restarts based on the system clock. The current method creates sporadic restart times.

I think this is an important option to have and I'm looking at a way to do this without changing the current Scheduling too much. I'm thinking we can add an option and a list of restart times to the conf file.

I'm working on a method that would take the soonest restart time from a list of times and find the time difference, then set the Scheduler interval to this difference.

**Comment by egebilecen** [comment]
Added in #95.
