### ISSUE TITLE
Admin Commands

### ISSUE THREAD

**Issue by 6--** [egebilecen/PZServerDiscordBot#9]
Hello,

Can you please add more commands to the bot?

More important is the /reloadoptions, changing settings while the server is online

Do you mind sharing your discord ID?

Thanks

<html><body>
<h2><span style="color: #00ccff;"><strong>LIST OF GENERAL COMMANDS</strong></span></h2>
<div class="alert alert-info"><strong>Note:</strong> When using commands from the Control Panel, you will not need to add a / before commands.</div>

NAME | DESCRIPTION | SYNTAX
-- | -- | --
additem | Gives an item to the player. | /additem “user” “module.item”
addvehicle | Spawns a vehicle. | /addvehicle “user”
addxp | Gives XP to a player. | /addxp “user” “perk=XP”
alarm | Sounds a building alarm at the admin’s position. Must be in a room. | /alarm
changeoption | Changes a server option. | /changeoption option="newOption"
chopper | Places a helicopter event on a random player. | /chopper
changepwd | Changes your password. | /changepwd “pwd” “newPwd”
createhorde | Spawns a horde near a player. | /createhorde “number”
godmode | Makes a player invincible. | /godmode “user”
gunshot | Makes a gunshot noise near the player. | /gunshot
help | Brings up the help menu. | /help
invisible | Makes a player invisible to zombies. | /invisible “user”
noclip | Allows a player to pass through solid objects. | /noclip “user”
quit | Saves and quits the server. | /quit
releasesafehouse | Releases a safehouse you own. | /releasesafehouse
reloadoptions | Reloads server options. | /reloadoptions
replay | Records and plays a replay for a moving player. | /replay “user” [-record \| -play \| -stop] “filename”
save | Saves the current world. | /save
sendpulse | Toggles sending server performance info to the client. | /sendpulse
showoptions | Shows a list of current server options and values. | /showoptions
startrain - stoprain | Starts and stops rain on the server. | /[start \| stop]rain
teleport | Teleports to a player. | /teleport “toUser” or /teleport “user” “toUser”
teleportto | Teleports to certain coordinates. | /teleportto x,y,z

</body>
</html>

<html><body>
<h2><span style="color: #00ccff;"><strong>LIST OF MODERATION COMMANDS:</strong></span></h2>

NAME | DESCRIPTION | SYNTAX
-- | -- | --
addalltowhitelist | Adds all current users connected with a password to the whitelist. | /addalltowhitelist
adduser | Adds a new user to the whitelist. | /adduser “user” “pwd”
addusertowhitelist - removeuserfromwhitelist | Adds/removes a single user connected with a password to the whitelist. | /addusertowhitelist “user”
banid - unbanid | Bans/unbans a Steam ID. | /[ban \| unban]id “SteamID”
banuser - unbanuser | Bans/unbans a user. | /[ban \| unban] “user”
grantadmin - removeadmin | Gives or removes admin rights to a user. | /[grantadmin \| removeadmin] “user”
kickuser | Kicks a user from the server. | /kickuser “user”
players | Lists all connected players. | /players
servermsg | Broadcast a message to all players. | /servermsg “message”
setaccesslevel | Set the access/permission level of a player. | /setaccesslevel “user” “[admin \| moderator \| overseer \| gm \| observer]”
voiceban | Ban a user from using the voice feature. | /voiceban “user” [-true \| -false]

</body>
</html>

**Comment by egebilecen** [comment]
Hey there. My discord ID is `Zaphiel#2702`. I will check the commands from the table you shared. Is the one you mentioned added recently? Because I don't remember seeing that one. Regardless, I will look into them.

**Comment by egebilecen** [comment]
completed in #11
