### ISSUE TITLE
Bot not working

### ISSUE THREAD

**Issue by Kir48** [egebilecen/PZServerDiscordBot#90]
Hello, I did everything according to the instructions, I created the bot and registered the token, but the bot is still offline in the discord

**Comment by egebilecen** [comment]
Hello. Could you share log file `pzbot.log`?

**Comment by Kir48** [comment]
[pzbot.log](https://github.com/egebilecen/PZServerDiscordBot/files/12458032/pzbot.log)

**Comment by egebilecen** [comment]
```
Exception: Discord.Net.WebSocketClosedException
Message: The server sent close 4014: "Disallowed intent(s)."
```
You did not configure the intents properly. See the warning below [here](https://github.com/egebilecen/PZServerDiscordBot#installing-bot-files).
