### ISSUE TITLE
Feature - Discord command to add/remove mods by providing the workshop link

### ISSUE THREAD

**Issue by DomicidalDesigns** [egebilecen/PZServerDiscordBot#91]
It would be nice to have a discord command to add mods by providing the mod link (or several links for adding multiple mods). This command would check if the server is shutdown, modify the servertest.ini file (under WorkshopItems and Mods), and then start the server.

### Obstacles:
- I believe the server **must** be shutdown before mods can be added/removed.
- Some mods have multiple Mod Ids for their optional add ons. I'm not sure how that could be handled. Checking the steamapp mod folder for mod.info files for optional add-ons and having a command flag to include these optional modIDs is a possible solution. I have a dirty python script that scrapes the workshop id and mod ids from the description but this is not ideal.

Thanks for the awesome bot. I don't have much experience with c# but I'd love to take a crack at adding features!

**Comment by egebilecen** [comment]
Completed in #93. Thank you for your contribution!
