### ISSUE TITLE
Localization of pt-BR

### ISSUE THREAD

**Issue by DeltaDinizzz** [egebilecen/PZServerDiscordBot#97]
As resquested in: https://github.com/egebilecen/PZServerDiscordBot#bot-commands

Translation of the .json Localization folder in pt-BR

[default.zip](https://github.com/egebilecen/PZServerDiscordBot/files/12565550/default.zip)

I saw that there is one already, sorry about that

**Comment by egebilecen** [comment]
Hey, which language is this?
