### ISSUE TITLE
automodupdate checker broken

### ISSUE THREAD

**Issue by lapochka8** [egebilecen/PZServerDiscordBot#99]
AutoModUpdate Checker no longer working properly as of V.11, have had to manually restart multiple times.

**Comment by egebilecen** [comment]
Hello, could you send me your pzbot.log file? You can attach it in comment.

**Comment by lapochka8** [comment]
[pzbot.log](https://github.com/egebilecen/PZServerDiscordBot/files/12708739/pzbot.log)

**Comment by lapochka8** [comment]
just switched back to v1.9.1 to see if that fixes it.

**Comment by egebilecen** [comment]
I see some request errors in the log. I am not sure what causes it because API is working just fine. Do let me know if the problem persists on older version.

**Comment by lapochka8** [comment]
will do, thank you.

**Comment by lapochka8** [comment]
Did not fix it, sorry it took me so long. Unsure whats bricking it.

**Comment by egebilecen** [comment]
I am not sure either. My guess is it's related to the host.
